import 'package:flutter/material.dart';

class DataForCosmic2{

  String? img;
  String? title;
  String? icon1;
  String? icon1text;
  String? icon1value;
  String? icon2;
  String? icon2text;
  String? icon2value;
  String? icon3;
  String? icon3text;
  String? icon3value;
  String? icon4;
  String? icon4text;
  String? icon4value;
  String? icon5;
  String? icon5text;
  String? icon5value;
  String? icon6;
  String? icon6text;
  String? icon6value;

  DataForCosmic2(
  {
    this.img,
    this.title,
    this.icon1,
    this.icon1text,
    this.icon1value,
    this.icon2,
    this.icon2text,
    this.icon2value,
    this.icon3,
    this.icon3text,
    this.icon3value,
    this.icon4,
    this.icon4text,
    this.icon4value,
    this.icon5,
    this.icon5text,
    this.icon5value,
    this.icon6,
    this.icon6text,
    this.icon6value
}
      );

  static List<DataForCosmic2> myList2 = [
    DataForCosmic2(
      img: "images/w6.png",
      title: "Mercury",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

    DataForCosmic2(
      img: "images/w6.png",
      title: "Venus",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

    DataForCosmic2(
      img: "images/w6.png",
      title: "Earth",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

    DataForCosmic2(
      img: "images/w6.png",
      title: "Mars",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

    DataForCosmic2(
      img: "images/w6.png",
      title: "Jupiter",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

    DataForCosmic2(
      img: "images/w6.png",
      title: "Saturn",
      icon1: "images/w21.png",
      icon1text: "Mass\n(10^24kg)",
      icon1value: "5.47",
      icon2: "images/w22.png",
      icon2text: "Gravity\n(m/s2)",
      icon2value: "9.8",
      icon3: "images/w23.png",
      icon3text: "Day\n(hours)",
      icon3value: "24",
      icon4: "images/w24.png",
      icon4text: "Esc. Velocity\n(km/s)",
      icon4value: "11.2",
      icon5: "images/w25.png",
      icon5text: "Mean\nTemp(C)",
      icon5value: "15",
      icon6: "images/w26.png",
      icon6text: "Distance from\nSun(106 km)",
      icon6value: "5.97",
    ),

  ];


}

// List<DataForCosmic2> myList2() {
//   return [
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
// DataForCosmic2(
// img: "images/w6.png",
// title: "Mercury",
// icon1: "images/w21.png",
// icon1text: "Mass\n(10^24kg)",
// icon1value: "5.47",
// icon2: "images/w22.png",
// icon2text: "Gravity\n(m/s2)",
// icon2value: "9.8",
// icon3: "images/w23.png",
// icon3text: "Day\n(hours)",
// icon3value: "24",
// icon4: "images/w24.png",
// icon4text: "Esc. Velocity\n(km/s)",
// icon4value: "11.2",
// icon5: "images/w25.png",
// icon5text: "Mean\nTemp(C)",
// icon5value: "15",
// icon6: "images/w26.png",
// icon6text: "Distance from\nSun(106 km)",
// icon6value: "5.97",
// ),
//
//   ];
// }
